spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:IE3-Backend}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
    hibernate:
      ddl-auto: create-drop

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      ProfileRoleUnique: PROFILE_ROLE_UNIQUE
      AlocationUserUnique: ALOCATION_USER_UNIQUE
      AlocationProjectUnique: ALOCATION_PROJECT_UNIQUE
springdoc:
  pathsToMatch: /, /api/**
